name: Linters
on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint check
        run: npx eslint "**/*.{js,jsx}"
      - name: Run Stylelint check
        run: npx stylelint "**/*.{css,scss}"
